### ISSUE TITLE
Peer review 

### ISSUE THREAD

**Issue by Mattsullivan2** [shalpern1/project#2]
Technical suggestions: 
1. Your picture gallery doesn't work. It appears the link is not working because when I click it then nothing happens. 
2. It appears that your logo is a little too big. This causes it to look out of line when looking at your headers. Try resizing it to better the visual. 

Content Suggestions: 
1. I think you could add additional information on the special events page. In its current form, it feels empty. 
2. On your reviews page, I think you should add past reviews and display them there to help build the brand. 

Overall this is a great website with a cool color scheme and great visuals. I am looking forward to seeing the final product.

**Comment by shalpern1** [comment]
Thank you for the feedback! Fixed all issues.
