### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by hansgbaum** [shalpern1/project#3]
Sammy, great job on your website, I really enjoyed the many visuals that sell your experience. 

Technical issues:

1. Your background image is not correctly adjusted to the full size of the webpage. I would recommend using a separate CSS page to style the background of every page.
2. The link in your picture gallery does not work, I would recommend checking the link or making sure the image files are correctly placed in your visual studio code.

Content issues:
1. I would heavily focus on adding more content to the review page as it is just an image. I think it's a big part of your business and is one of the pages that would be checked the most.
2. I would also suggest styling your menu slightly differently so it's more legible. The words go over the pictures and with their dark blue font, it is hard to read sometimes.

Overall your website is looking very good. I really like your constant use of pictures and the also the business itself.

**Comment by shalpern1** [comment]
Thank you for the feedback. Fixed all issues!
